    - name: Delete previous images from ECR (except current tag)
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        echo "Deleting old images from ECR repository: $ECR_REPOSITORY"

        # Get list of image tags except the current one
        IMAGES_TO_DELETE=$(aws ecr list-images \
          --region $AWS_REGION \
          --repository-name $ECR_REPOSITORY \
          --query "imageIds[?imageTag!=\`$IMAGE_TAG\`]" \
          --output json)

        if [ "$IMAGES_TO_DELETE" != "[]" ]; then
          echo "Deleting images: $IMAGES_TO_DELETE"
          aws ecr batch-delete-image \
            --region $AWS_REGION \
            --repository-name $ECR_REPOSITORY \
            --image-ids "$IMAGES_TO_DELETE"
        else
          echo "No images to delete."
        fi
